var annotated_dup =
[
    [ "al", "namespaceal.html", "namespaceal" ],
    [ "gam", null, [
      [ "acc", null, [
        [ "Clip", "structgam_1_1acc_1_1_clip.html", null ],
        [ "None", "structgam_1_1acc_1_1_none.html", null ],
        [ "Wrap", "structgam_1_1acc_1_1_wrap.html", null ]
      ] ],
      [ "gen", "namespacegam_1_1gen.html", "namespacegam_1_1gen" ],
      [ "ipl", "namespacegam_1_1ipl.html", "namespacegam_1_1ipl" ],
      [ "iplSeq", null, [
        [ "Base", "structgam_1_1ipl_seq_1_1_base.html", "structgam_1_1ipl_seq_1_1_base" ],
        [ "Cosine", "structgam_1_1ipl_seq_1_1_cosine.html", "structgam_1_1ipl_seq_1_1_cosine" ],
        [ "Cubic", "structgam_1_1ipl_seq_1_1_cubic.html", "structgam_1_1ipl_seq_1_1_cubic" ],
        [ "Linear", "structgam_1_1ipl_seq_1_1_linear.html", "structgam_1_1ipl_seq_1_1_linear" ],
        [ "None", "structgam_1_1ipl_seq_1_1_none.html", "structgam_1_1ipl_seq_1_1_none" ],
        [ "Round", "structgam_1_1ipl_seq_1_1_round.html", "structgam_1_1ipl_seq_1_1_round" ],
        [ "Trunc", "structgam_1_1ipl_seq_1_1_trunc.html", "structgam_1_1ipl_seq_1_1_trunc" ]
      ] ],
      [ "phsInc", null, [
        [ "Loop", "structgam_1_1phs_inc_1_1_loop.html", "structgam_1_1phs_inc_1_1_loop" ],
        [ "NShot", "structgam_1_1phs_inc_1_1_n_shot.html", "structgam_1_1phs_inc_1_1_n_shot" ],
        [ "OneShot", "structgam_1_1phs_inc_1_1_one_shot.html", "structgam_1_1phs_inc_1_1_one_shot" ],
        [ "PingPong", "structgam_1_1phs_inc_1_1_ping_pong.html", "structgam_1_1phs_inc_1_1_ping_pong" ],
        [ "Pulse", "structgam_1_1phs_inc_1_1_pulse.html", "structgam_1_1phs_inc_1_1_pulse" ],
        [ "Rhythm", "structgam_1_1phs_inc_1_1_rhythm.html", "structgam_1_1phs_inc_1_1_rhythm" ]
      ] ],
      [ "scl", "namespacegam_1_1scl.html", "namespacegam_1_1scl" ],
      [ "Accum", "classgam_1_1_accum.html", "classgam_1_1_accum" ],
      [ "AccumPhase", "classgam_1_1_accum_phase.html", "classgam_1_1_accum_phase" ],
      [ "AD", "classgam_1_1_a_d.html", "classgam_1_1_a_d" ],
      [ "ADSR", "classgam_1_1_a_d_s_r.html", "classgam_1_1_a_d_s_r" ],
      [ "Allocator", "classgam_1_1_allocator.html", "classgam_1_1_allocator" ],
      [ "Allocator< void >", "classgam_1_1_allocator_3_01void_01_4.html", "classgam_1_1_allocator_3_01void_01_4" ],
      [ "AllPass1", "classgam_1_1_all_pass1.html", "classgam_1_1_all_pass1" ],
      [ "AllPass2", "classgam_1_1_all_pass2.html", "classgam_1_1_all_pass2" ],
      [ "AM", "classgam_1_1_a_m.html", "classgam_1_1_a_m" ],
      [ "Array", "classgam_1_1_array.html", "classgam_1_1_array" ],
      [ "ArrayBase", "classgam_1_1_array_base.html", "classgam_1_1_array_base" ],
      [ "ArrayPow2", "classgam_1_1_array_pow2.html", "classgam_1_1_array_pow2" ],
      [ "AudioCallback", "classgam_1_1_audio_callback.html", "classgam_1_1_audio_callback" ],
      [ "AudioDevice", "classgam_1_1_audio_device.html", "classgam_1_1_audio_device" ],
      [ "AudioIO", "classgam_1_1_audio_i_o.html", "classgam_1_1_audio_i_o" ],
      [ "AudioIOData", "classgam_1_1_audio_i_o_data.html", "classgam_1_1_audio_i_o_data" ],
      [ "Biquad", "classgam_1_1_biquad.html", "classgam_1_1_biquad" ],
      [ "Biquad3", "classgam_1_1_biquad3.html", "classgam_1_1_biquad3" ],
      [ "BlockDC", "classgam_1_1_block_d_c.html", "classgam_1_1_block_d_c" ],
      [ "BlockNyq", "classgam_1_1_block_nyq.html", "classgam_1_1_block_nyq" ],
      [ "Burst", "classgam_1_1_burst.html", "classgam_1_1_burst" ],
      [ "Buzz", "classgam_1_1_buzz.html", "classgam_1_1_buzz" ],
      [ "CFFT", "classgam_1_1_c_f_f_t.html", "classgam_1_1_c_f_f_t" ],
      [ "ChebyN", "classgam_1_1_cheby_n.html", "classgam_1_1_cheby_n" ],
      [ "Chirp", "classgam_1_1_chirp.html", "classgam_1_1_chirp" ],
      [ "Chirplet", "classgam_1_1_chirplet.html", "classgam_1_1_chirplet" ],
      [ "Chorus", "classgam_1_1_chorus.html", "classgam_1_1_chorus" ],
      [ "Comb", "classgam_1_1_comb.html", "classgam_1_1_comb" ],
      [ "Complex", "classgam_1_1_complex.html", "classgam_1_1_complex" ],
      [ "ControlFunc", "classgam_1_1_control_func.html", "classgam_1_1_control_func" ],
      [ "CSine", "classgam_1_1_c_sine.html", "classgam_1_1_c_sine" ],
      [ "CSinTable", "classgam_1_1_c_sin_table.html", "classgam_1_1_c_sin_table" ],
      [ "Curve", "classgam_1_1_curve.html", "classgam_1_1_curve" ],
      [ "Decay", "classgam_1_1_decay.html", "classgam_1_1_decay" ],
      [ "Delay", "classgam_1_1_delay.html", "classgam_1_1_delay" ],
      [ "Delay1", "classgam_1_1_delay1.html", "classgam_1_1_delay1" ],
      [ "Delay2", "classgam_1_1_delay2.html", "classgam_1_1_delay2" ],
      [ "DelayN", "structgam_1_1_delay_n.html", "structgam_1_1_delay_n" ],
      [ "DelayShift", "classgam_1_1_delay_shift.html", "classgam_1_1_delay_shift" ],
      [ "DFT", "classgam_1_1_d_f_t.html", "classgam_1_1_d_f_t" ],
      [ "DFTBase", "classgam_1_1_d_f_t_base.html", "classgam_1_1_d_f_t_base" ],
      [ "Differencer", "classgam_1_1_differencer.html", "classgam_1_1_differencer" ],
      [ "Dist", "classgam_1_1_dist.html", "classgam_1_1_dist" ],
      [ "Domain", "classgam_1_1_domain.html", "classgam_1_1_domain" ],
      [ "Domain1", "classgam_1_1_domain1.html", "classgam_1_1_domain1" ],
      [ "DomainObserver", "classgam_1_1_domain_observer.html", "classgam_1_1_domain_observer" ],
      [ "DoubleRing", "classgam_1_1_double_ring.html", "classgam_1_1_double_ring" ],
      [ "DSF", "classgam_1_1_d_s_f.html", "classgam_1_1_d_s_f" ],
      [ "DWO", "classgam_1_1_d_w_o.html", "classgam_1_1_d_w_o" ],
      [ "Echo", "classgam_1_1_echo.html", "classgam_1_1_echo" ],
      [ "EchoCSine", "classgam_1_1_echo_c_sine.html", "classgam_1_1_echo_c_sine" ],
      [ "Env", "classgam_1_1_env.html", "classgam_1_1_env" ],
      [ "EnvFollow", "classgam_1_1_env_follow.html", "classgam_1_1_env_follow" ],
      [ "Filter2", "classgam_1_1_filter2.html", "classgam_1_1_filter2" ],
      [ "FreqShift", "classgam_1_1_freq_shift.html", "classgam_1_1_freq_shift" ],
      [ "Func", "classgam_1_1_func.html", "classgam_1_1_func" ],
      [ "Gate", "classgam_1_1_gate.html", "classgam_1_1_gate" ],
      [ "Hilbert", "classgam_1_1_hilbert.html", "classgam_1_1_hilbert" ],
      [ "Impulse", "structgam_1_1_impulse.html", "structgam_1_1_impulse" ],
      [ "IndexMap", "classgam_1_1_index_map.html", "classgam_1_1_index_map" ],
      [ "Integrator", "classgam_1_1_integrator.html", "classgam_1_1_integrator" ],
      [ "LFO", "classgam_1_1_l_f_o.html", "classgam_1_1_l_f_o" ],
      [ "LookupTable", "classgam_1_1_lookup_table.html", "classgam_1_1_lookup_table" ],
      [ "Loop1P", "classgam_1_1_loop1_p.html", "classgam_1_1_loop1_p" ],
      [ "Loop1P1Z", "classgam_1_1_loop1_p1_z.html", "classgam_1_1_loop1_p1_z" ],
      [ "LoopGain", "classgam_1_1_loop_gain.html", "classgam_1_1_loop_gain" ],
      [ "MonoSynth", "classgam_1_1_mono_synth.html", "classgam_1_1_mono_synth" ],
      [ "MovingAvg", "classgam_1_1_moving_avg.html", "classgam_1_1_moving_avg" ],
      [ "Multitap", "classgam_1_1_multitap.html", "classgam_1_1_multitap" ],
      [ "NamedElems", "structgam_1_1_named_elems.html", "structgam_1_1_named_elems" ],
      [ "NamedElems< 0, T >", "structgam_1_1_named_elems_3_010_00_01_t_01_4.html", null ],
      [ "NamedElems< 1, T >", "structgam_1_1_named_elems_3_011_00_01_t_01_4.html", "structgam_1_1_named_elems_3_011_00_01_t_01_4" ],
      [ "NamedElems< 2, T >", "structgam_1_1_named_elems_3_012_00_01_t_01_4.html", "structgam_1_1_named_elems_3_012_00_01_t_01_4" ],
      [ "NamedElems< 3, T >", "structgam_1_1_named_elems_3_013_00_01_t_01_4.html", "structgam_1_1_named_elems_3_013_00_01_t_01_4" ],
      [ "NamedElems< 4, T >", "structgam_1_1_named_elems_3_014_00_01_t_01_4.html", "structgam_1_1_named_elems_3_014_00_01_t_01_4" ],
      [ "Node2", "classgam_1_1_node2.html", "classgam_1_1_node2" ],
      [ "Node3", "classgam_1_1_node3.html", "classgam_1_1_node3" ],
      [ "NoiseBrown", "classgam_1_1_noise_brown.html", "classgam_1_1_noise_brown" ],
      [ "NoisePink", "classgam_1_1_noise_pink.html", "classgam_1_1_noise_pink" ],
      [ "NoiseViolet", "classgam_1_1_noise_violet.html", "classgam_1_1_noise_violet" ],
      [ "NoiseWhite", "classgam_1_1_noise_white.html", "classgam_1_1_noise_white" ],
      [ "Notch", "classgam_1_1_notch.html", "classgam_1_1_notch" ],
      [ "OnePole", "classgam_1_1_one_pole.html", "classgam_1_1_one_pole" ],
      [ "Osc", "classgam_1_1_osc.html", "classgam_1_1_osc" ],
      [ "Pan", "classgam_1_1_pan.html", "classgam_1_1_pan" ],
      [ "Pluck", "classgam_1_1_pluck.html", "classgam_1_1_pluck" ],
      [ "Polar", "structgam_1_1_polar.html", "structgam_1_1_polar" ],
      [ "Process", "classgam_1_1_process.html", "classgam_1_1_process" ],
      [ "ProcessNode", "classgam_1_1_process_node.html", "classgam_1_1_process_node" ],
      [ "Quantizer", "classgam_1_1_quantizer.html", "classgam_1_1_quantizer" ],
      [ "Recorder", "classgam_1_1_recorder.html", "classgam_1_1_recorder" ],
      [ "Reson", "classgam_1_1_reson.html", "classgam_1_1_reson" ],
      [ "ReverbMS", "classgam_1_1_reverb_m_s.html", "classgam_1_1_reverb_m_s" ],
      [ "RFFT", "classgam_1_1_r_f_f_t.html", "classgam_1_1_r_f_f_t" ],
      [ "Ring", "classgam_1_1_ring.html", "classgam_1_1_ring" ],
      [ "RNGLinCon", "classgam_1_1_r_n_g_lin_con.html", "classgam_1_1_r_n_g_lin_con" ],
      [ "RNGMulLinCon", "classgam_1_1_r_n_g_mul_lin_con.html", "classgam_1_1_r_n_g_mul_lin_con" ],
      [ "RNGTaus", "classgam_1_1_r_n_g_taus.html", "classgam_1_1_r_n_g_taus" ],
      [ "SamplePlayer", "classgam_1_1_sample_player.html", "classgam_1_1_sample_player" ],
      [ "Saw", "structgam_1_1_saw.html", "structgam_1_1_saw" ],
      [ "Scheduler", "classgam_1_1_scheduler.html", "classgam_1_1_scheduler" ],
      [ "SchedulerAudioIOData", "structgam_1_1_scheduler_audio_i_o_data.html", "structgam_1_1_scheduler_audio_i_o_data" ],
      [ "Seg", "classgam_1_1_seg.html", "classgam_1_1_seg" ],
      [ "SegExp", "classgam_1_1_seg_exp.html", "classgam_1_1_seg_exp" ],
      [ "SilenceDetect", "classgam_1_1_silence_detect.html", "classgam_1_1_silence_detect" ],
      [ "Sine", "classgam_1_1_sine.html", "classgam_1_1_sine" ],
      [ "SineD", "classgam_1_1_sine_d.html", "classgam_1_1_sine_d" ],
      [ "SineDs", "classgam_1_1_sine_ds.html", "classgam_1_1_sine_ds" ],
      [ "SineR", "classgam_1_1_sine_r.html", "classgam_1_1_sine_r" ],
      [ "SineRs", "classgam_1_1_sine_rs.html", "classgam_1_1_sine_rs" ],
      [ "SizeArray", "structgam_1_1_size_array.html", "structgam_1_1_size_array" ],
      [ "SizeArrayPow2", "structgam_1_1_size_array_pow2.html", "structgam_1_1_size_array_pow2" ],
      [ "Slice", "classgam_1_1_slice.html", "classgam_1_1_slice" ],
      [ "SlidingDFT", "classgam_1_1_sliding_d_f_t.html", "classgam_1_1_sliding_d_f_t" ],
      [ "SlidingWindow", "classgam_1_1_sliding_window.html", "classgam_1_1_sliding_window" ],
      [ "SoundFile", "classgam_1_1_sound_file.html", "classgam_1_1_sound_file" ],
      [ "Square", "structgam_1_1_square.html", "structgam_1_1_square" ],
      [ "STFT", "classgam_1_1_s_t_f_t.html", "classgam_1_1_s_t_f_t" ],
      [ "Sweep", "classgam_1_1_sweep.html", "classgam_1_1_sweep" ],
      [ "TablePow2", "classgam_1_1_table_pow2.html", "classgam_1_1_table_pow2" ],
      [ "Thread", "classgam_1_1_thread.html", "classgam_1_1_thread" ],
      [ "Threshold", "classgam_1_1_threshold.html", "classgam_1_1_threshold" ],
      [ "Timer", "classgam_1_1_timer.html", "classgam_1_1_timer" ],
      [ "TransferFunc", "classgam_1_1_transfer_func.html", "classgam_1_1_transfer_func" ],
      [ "Twiddle", "structgam_1_1_twiddle.html", null ],
      [ "Twiddle< double >", "structgam_1_1_twiddle_3_01double_01_4.html", "structgam_1_1_twiddle_3_01double_01_4" ],
      [ "Twiddle< float >", "structgam_1_1_twiddle_3_01float_01_4.html", "structgam_1_1_twiddle_3_01float_01_4" ],
      [ "UnitMapper", "classgam_1_1_unit_mapper.html", "classgam_1_1_unit_mapper" ],
      [ "Upsample", "classgam_1_1_upsample.html", "classgam_1_1_upsample" ],
      [ "Vec", "classgam_1_1_vec.html", "classgam_1_1_vec" ],
      [ "Vowel", "classgam_1_1_vowel.html", "classgam_1_1_vowel" ],
      [ "ZeroCross", "classgam_1_1_zero_cross.html", "classgam_1_1_zero_cross" ],
      [ "ZeroCrossRate", "classgam_1_1_zero_cross_rate.html", "classgam_1_1_zero_cross_rate" ]
    ] ],
    [ "AlloArray", "struct_allo_array.html", "struct_allo_array" ],
    [ "AlloArrayHeader", "struct_allo_array_header.html", "struct_allo_array_header" ],
    [ "AlloArrayWrapper", "struct_allo_array_wrapper.html", "struct_allo_array_wrapper" ],
    [ "CSVReader", "class_c_s_v_reader.html", "class_c_s_v_reader" ],
    [ "lighting_shader_uniforms", "structlighting__shader__uniforms.html", "structlighting__shader__uniforms" ],
    [ "material_uniform_locations", "structmaterial__uniform__locations.html", "structmaterial__uniform__locations" ],
    [ "per_light_uniform_locations", "structper__light__uniform__locations.html", "structper__light__uniform__locations" ],
    [ "SerHeader", "struct_ser_header.html", "struct_ser_header" ]
];